# Day 3

### Expectation

1. Fully understand Functions in Python
2. Introduction to Numpy
3. Introduction to Pandas

### Refresher on Functions

what are functions?

header and body

In [8]:
# simply function

def simple():
    
    return "Am the simplest you can ever get on planet earth"

simple()

'Am the simplest you can ever get on planet earth'

In [10]:
a = 1
f = 0
def reply():
    
    if a == 1:
        if f==0:
            print("Dude this event is for ladies, dont bring your ..... there")
        else:
            print("thanks Man for coming to facilitate, it at level 5 block b college of computing")
            
    else:
        
        print("Thanks madam for picking interest in pyladies, it is at block b level 5 college of computing")
        
reply()

Dude this event is for ladies, dont bring your ..... there


In [11]:
# refresher, write your own crazy function



In [12]:
def salaryEarned(currency,ammount):
    
    if currency == "USD":
        
        return "$" + str(ammount)
    
    elif currency == "EURO":
        
        return "£" + str(ammount)
    
    elif currency == "KSH":
        
        return "ksh" + str(ammount)
    
    else:
        
        return "ugx" + str(ammount)
    
salaryEarned("USD", 4000)

'$4000'

exercise 1 

write a function to add 2 numbers given as arguments

exercise 2 

write a function which will check if today and the remaining days we shall finish on time

Hint you will have to check the time

#### Interesting Stuff now 

#### Numpy
sudo apt-get install numpy

In [13]:
import numpy as np

In [14]:
# lets create two lists

l = [1,2,3,4,5]
a = np.array([1,2,3,4,5])

In [20]:
# lets loop on all of them

for each in l:
    print(each)
    


1
2
3
4
5


In [21]:
for each in a:
    print(each)

1
2
3
4
5


In [23]:
# what if you want to add another element

l.append(6)
l

[1, 2, 3, 4, 5, 6, 6]

In [24]:
a.append(6)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [25]:
l = l+ [7]
l

[1, 2, 3, 4, 5, 6, 6, 7]

In [28]:
a = a+ [6,7]
a

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

In [29]:
a = a + [8]
a

array([23, 24, 25, 26, 27])

In [31]:
l = l+ [8]
l

[1, 2, 3, 4, 5, 6, 6, 7, 8]

In [32]:
a = a * 3
a

array([69, 72, 75, 78, 81])

In [35]:
l = l * 2
l

[1,
 2,
 3,
 4,
 5,
 6,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 6,
 7,
 8]

In [36]:
# assume we are interested in powering our values

a ** 2

array([4761, 5184, 5625, 6084, 6561])

In [37]:
l ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [41]:
# we can still power a list

for e in l:
    
    l.append(e*e)

l

KeyboardInterrupt: 

In [50]:
# speed comparision between for loop and numpy methods

import numpy as np
from datetime import datetime

a = np.random.rand(100)
b = np.random.rand(100)
T = 100000

def slow_one(a,b):    
    result = 0    
    for e,f in zip(a,b):
        result = + e*f
        return result
    
t0 = datetime.now()
    
for t in range(T):
    slow_one(a,b)
        
dt1 = datetime.now()- t0    
    
t0 = datetime.now()
    
for t in range(T):
    a.dot(b)        
dt2 = datetime.now()- t0
    
print(dt1.total_seconds()/dt2.total_seconds()) 

1.064804495892971


#### Pandas
the goal of this part is not to show everything pandas can do but to introduce you to reading data with pandas, we shall break down other parts of pandas in the next class.

common data formats

1. csv(comma separated value)
2. excel
3. json
4. spss and Stata

In [ ]:
# Reading csv


In [ ]:
# excel


In [ ]:
# reading json
